# This file is autogenerated by generate_sql_fwd_declaration.py
# do not edit it manually
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import ARRAY, BIGINT, BINARY, BLOB, BOOLEAN, BigInteger, Binary, Boolean, CHAR, CLOB, CheckConstraint, Column, ColumnDefault, Computed, Constraint, DATE, DATETIME, DDL, DECIMAL, Date, DateTime, DefaultClause, Enum, FLOAT, FetchedValue, Float, ForeignKey, ForeignKeyConstraint, INTEGER, INTEGER, IdentityOptions, Index, Integer, Interval, JSON, LargeBinary, MetaData, NCHAR, NUMERIC, NVARCHAR, Numeric, PassiveDefault, PickleType, PrimaryKeyConstraint, REAL, SMALLINT, Sequence, SmallInteger, String, TEXT, TIME, TIMESTAMP, Table, Text, ThreadLocalMetaData, Time, TypeDecorator, Unicode, UnicodeText, UniqueConstraint, VARBINARY, VARCHAR
from sqlalchemy.orm import AliasOption, AttributeExtension, Bundle, ColumnProperty, ComparableProperty, CompositeProperty, Load, Mapper, MapperExtension, PropComparator, Query, RelationshipProperty, Session, SessionExtension, SynonymProperty, scoped_session, sessionmaker


class SQL(SQLAlchemy):
    ARRAY = ARRAY
    BIGINT = BIGINT
    BINARY = BINARY
    BLOB = BLOB
    BOOLEAN = BOOLEAN
    BigInteger = BigInteger
    Binary = Binary
    Boolean = Boolean
    CHAR = CHAR
    CLOB = CLOB
    CheckConstraint = CheckConstraint
    Column = Column
    ColumnDefault = ColumnDefault
    Computed = Computed
    Constraint = Constraint
    DATE = DATE
    DATETIME = DATETIME
    DDL = DDL
    DECIMAL = DECIMAL
    Date = Date
    DateTime = DateTime
    DefaultClause = DefaultClause
    Enum = Enum
    FLOAT = FLOAT
    FetchedValue = FetchedValue
    Float = Float
    ForeignKey = ForeignKey
    ForeignKeyConstraint = ForeignKeyConstraint
    INT = INTEGER
    INTEGER = INTEGER
    IdentityOptions = IdentityOptions
    Index = Index
    Integer = Integer
    Interval = Interval
    JSON = JSON
    LargeBinary = LargeBinary
    MetaData = MetaData
    NCHAR = NCHAR
    NUMERIC = NUMERIC
    NVARCHAR = NVARCHAR
    Numeric = Numeric
    PassiveDefault = PassiveDefault
    PickleType = PickleType
    PrimaryKeyConstraint = PrimaryKeyConstraint
    REAL = REAL
    SMALLINT = SMALLINT
    Sequence = Sequence
    SmallInteger = SmallInteger
    String = String
    TEXT = TEXT
    TIME = TIME
    TIMESTAMP = TIMESTAMP
    Table = Table
    Text = Text
    ThreadLocalMetaData = ThreadLocalMetaData
    Time = Time
    TypeDecorator = TypeDecorator
    Unicode = Unicode
    UnicodeText = UnicodeText
    UniqueConstraint = UniqueConstraint
    VARBINARY = VARBINARY
    VARCHAR = VARCHAR
    AliasOption = AliasOption
    AttributeExtension = AttributeExtension
    Bundle = Bundle
    ColumnProperty = ColumnProperty
    ComparableProperty = ComparableProperty
    CompositeProperty = CompositeProperty
    Load = Load
    Mapper = Mapper
    MapperExtension = MapperExtension
    PropComparator = PropComparator
    Query = Query
    RelationshipProperty = RelationshipProperty
    Session = Session
    SessionExtension = SessionExtension
    SynonymProperty = SynonymProperty
    scoped_session = scoped_session
    sessionmaker = sessionmaker
